"""Test cases for autogenerated comments."""
from .lib import eq_


def test_basic_comment():
    """Test basic comment generation."""
    eq_("# Test", "# Test")


def test_multiline_comment():
    """Test multiline comment generation."""
    eq_("# Line 1\n# Line 2", "# Line 1\n# Line 2")


def test_empty_comment():
    """Test empty comment generation."""
    eq_("#", "#")


def test_indented_comment():
    """Test indented comment generation."""
    eq_("    # Test", "    # Test")


def test_comment_with_special_chars():
    """Test comment with special characters."""
    eq_("# Test: !@#$%^&*()", "# Test: !@#$%^&*()")


def test_comment_with_unicode():
    """Test comment with unicode characters."""
    eq_("# Test: 你好", "# Test: 你好")


def test_comment_with_trailing_whitespace():
    """Test comment with trailing whitespace."""
    eq_("# Test  ", "# Test  ")


def test_comment_with_leading_whitespace():
    """Test comment with leading whitespace."""
    eq_("#  Test", "#  Test")


def test_comment_with_multiple_hashes():
    """Test comment with multiple hash symbols."""
    eq_("## Test", "## Test")


def test_comment_with_empty_lines():
    """Test comment with empty lines."""
    eq_("# Line 1\n\n# Line 2", "# Line 1\n\n# Line 2")
